[package]
name = "behaviortree-rs"
description = "Rust implementation of BehaviorTree.CPP, a robust behavior tree library in C++"
version = "0.2.5-alpha3"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
behaviortree-rs-derive = { path = "../behaviortree-rs-derive" }
# behaviortree-rs-derive = "0.2.5-alpha3"
evalexpr = { version = "12.0.1", optional = true }
log = "0.4.22"
ouroboros = "0.18.5"
parking_lot = "0.12.3"
quick-xml = { version = "0.37.2", features = ["serde", "serialize"] }
smallvec = "1.14.0"
thiserror = "1.0.47"
typed-builder = "0.20.0"
winnow = "0.7.3"

[dev-dependencies]
criterion = "0.5.1"
pretty_env_logger = "0.5.0"
rstest = "0.23.0"
tokio = { version = "1.43.0", features = ["rt", "macros"] }

[features]
expr = ["dep:evalexpr"]

[[bench]]
name = "ticking"
harness = false

[[bench]]
name = "blackboard"
harness = false

[[bench]]
name = "parsing"
harness = false
